"use client"

import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"

export default function InstructionsPage() {
  const router = useRouter()

  return (
    <div className="flex justify-center items-center min-h-screen px-4 py-12">
      <div className="w-full max-w-2xl">
        <Card className="modern-card card-hover">
          <CardHeader className="text-center space-y-2">
            <CardTitle className="text-3xl font-bold">
              <span className="gradient-text">Instructions</span>
            </CardTitle>
            <CardDescription className="text-gray-500">Please read carefully before proceeding</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-3">
              <h3 className="text-lg font-semibold text-blue-600">How the Test Works:</h3>
              <ol className="list-decimal pl-6 space-y-2 text-gray-700">
                <li>You will go through 10 questions, each showing a low-quality OCT image (ART10).</li>
                <li>
                  For each image, 5 enhanced versions—generated by 5 different AI models—will be displayed at the bottom
                  of the screen.
                </li>
                <li>
                  A "Comparison Area" at the top of the screen can be used to visualise an enhanced image (selected from
                  below) in more detail and compare it side-by-side with the low-quality counterpart in their native
                  resolution.
                </li>
                <ul className="list-disc list-inside pl-4 mt-1">
                  <li>
                    This area can also be used to compare two enhanced images with each other, by just clicking back and
                    forth between them (from below) to spot differences more easily.{" "}
                  </li>
                </ul>
                <li>
                  At the bottom of the screen, rank the 5 enhanced versions from best (lefright) to worst (5) by
                  drag-and-drop, based on which ones you think are the best enhanced versions of the low-quality ART10
                  (see evaluation criteria in the section below).
                </li>
                <ul className="list-disc list-inside pl-4 mt-1">
                  <li>
                    If you take the test from a touchscreen, you just have to click on the letters of the two images you
                    want to swap instead of drag-and-drop.
                  </li>
                </ul>
                <li>Submit your ranking for each question to proceed to the next.</li>
                <li>All 10 questions must be completed before final submission.</li>
              </ol>
            </div>

            <div className="space-y-3">
              <h3 className="text-lg font-semibold text-blue-600">Evaluation Criteria:</h3>
              <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-md shadow-sm">
                <div className="flex items-start">
                  <div className="flex-shrink-0 mt-0.5">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5 text-blue-600"
                      viewBox="0 0 20 20"
                      fill="currentColor"
                    >
                      <path
                        fillRule="evenodd"
                        d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </div>
                  <div className="ml-3">
                    <p className="text-sm font-medium text-blue-800 mb-2">
                      When ranking the enhanced images, please consider:
                    </p>
                    <ul className="list-disc pl-5 space-y-1 text-gray-700">
                      <li>Reduction of speckle noise</li>
                      <li>Removal of motion artifacts</li>
                      <li>
                        Preservation of anatomical features and structures (no introduction of new artifacts or
                        obscuration of anatomical features)
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex justify-center pt-2">
            <Button onClick={() => router.push("/practice")} size="lg" className="button-gradient">
              Try Practice Question
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}
