"use client"

import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"

export default function InstructionsPage() {
  const router = useRouter()

  return (
    <div className="flex justify-center items-center min-h-screen px-4 py-12">
      <div className="w-full max-w-2xl">
        <Card className="modern-card card-hover">
          <CardHeader className="text-center space-y-2">
            <CardTitle className="text-3xl font-bold">
              <span className="gradient-text">Instructions</span>
            </CardTitle>
            <CardDescription className="text-gray-500">Please read carefully before proceeding</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-3">
              <h3 className="text-lg font-semibold text-blue-600">How the Test Works:</h3>
              <ol className="list-decimal pl-6 space-y-2 text-gray-700">
                <li>You will go through 10 questions, each showing a low-quality OCT image (ART10).</li>
                <li>For each image, 5 enhanced versions—generated by 5 different AI models—will be displayed at the bottom of the screen.</li>
                <li>A "Comparison Area" at the top of the screen can be used to visualise an enhanced image (selected from below) in more detail and compare it side-by-side with the low-quality counterpart in their native resolution.</li>
                  <ul className="list-disc list-inside pl-4 mt-1">
                    <li>This area can also be used to compare two enhanced images with each other, by just clicking back and forth between them (from below) to spot differences more easily. </li>
                  </ul>
                <li>At the bottom of the screen, rank the 5 enhanced versions from best (1) to worst (5) by drag-and-drop, based on which ones you think are the best enhanced versions of the low-quality ART10 (see evaluation criteria in the section below).</li>
                  <ul className="list-disc list-inside pl-4 mt-1">
                    <li>If you take the test from a touchscreen, you just have to click on the letters of the two images you want to swap instead of drag-and-drop.</li>
                  </ul>
                <li>Submit your ranking for each question to proceed to the next.</li>
                <li>All 10 questions must be completed before final submission.</li>
              </ol>
            </div>

            <div className="space-y-3">
              <h3 className="text-lg font-semibold text-blue-600">Evaluation Criteria:</h3>
              <p className="mb-2 text-gray-700">When ranking the enhanced images, please consider:</p>
              <ul className="list-disc pl-6 space-y-1 text-gray-700">
                <li>Reduction of speckle noise</li>
                <li>Removal of motion artifacts</li>
                <li>
                  Preservation of anatomical features and structures (no introduction of new artifacts or obscuration of
                  anatomical features)
                </li>
              </ul>
            </div>
          </CardContent>
          <CardFooter className="flex justify-center pt-2">
            <Button onClick={() => router.push("/practice")} size="lg" className="button-gradient">
              Try Practice Question
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}
